# api_id: 12622619
api_id: 18031383
# api_hash: "8b71b8c43075941645017b5e163b4971"
api_hash: "ca3e473a2237fdd835cb1f85fc419d6b"
session_name: "ryan_v404"
bot_token: "5266680121:AAFNZ-7Md81Og0nFkDZLMg-dosG0NOoY-SE"

# The channel names that you'd like to forward messages from.
# The user running the client must have these channels present on it's dialogs.
input_channel_names:
  - "ChDambiev"
  - "Doninside"
  - "MFARussia"
  - "Murad_Gazdiev"
  - "OpenUkraine"
  - "RVvoenkor"
  - "RtrDonetsk"
  - "RusMissionOSCE"
  # - "RusTroyka"
  - "SIL0VIKI"
  - "SergeyKolyasnikov"
  - "Soldieroffortune777"
  - "SonOfMonarchy"
  - "WarDonbass"
  - "Za_Derjavy"
  - "astramilitarum"
  - "bbbreaking"
  - "bditelnost"
  - "boris_rozhin"
  - "chesnokmedia"
  - "cyber_frontZ"
  - "daokedao"
  - "donbass_photos"
  - "donbassinsider"
  - "donetsk_donbass"
  - "dplatonova"
  - "galulala"
  - "ghost_of_novorossia"
  - "grey_zone"
  - "hackberegini"
  - "intelslava"
  - "livenec"
  - "madam_secretar"
  - "margaritasimonyan"
  - "martovalieva1"
  - "mig41"
  - "mikayelbad"
  - "milchronicles"
  - "milinfolive"
  - "mosregtoday"
  - "neoficialniybezsonov"
  - "notes_veterans"
  - "npo_dvina"
  - "opersvodki"
  - "opyat22"
  - "orda_mordora"
  - "panteri_panteri"
  - "rf200_now1"
  - "rgrunews"
  - "rian_ru"
  - "rlz_the_kraken"
  - "rusmonstr"
  - "russ_orientalist"
  - "russica2"
  - "rybar"
  - "sashakots"
  - "soldiers_truth"
  - "spletnicca"
  - "stepnoy_veter"
  - "surf_noise1"
  - "svarschiki"
  - "vladlentatarsky"
  - "voenacher"
  - "warfakes"
  - "warwebm"
  - "z_kharkovnash"

# The output channel names that the messages will be forwarded to.
# The user running the client must have a write access to those channels, and have the channels present on theirs dialogs.
output_channel_names:
  - "ryan_test_channel"

# The channel IDs that you'd like to forward messages from. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
input_channel_ids: # Input Channel ID without quotes ''
  - 1218410161
  - 1138914412
  - 1074511071
  - 1451734813
  - 1200595041
  - 1355540894
  - 1464146642
  - 1514685631
  # BAD CHANNEL LINK - https://t.me/RusTroyka
  - 1246399946
  - 1012103617
  - 1168636470
  - 1136444638
  - 1248668939
  - 1165131018
  - 1321658383
  - 1394050290
  - 1208211067
  - 1101806611
  - 1108403053
  - 1283016748
  - 1053161069
  - 1490843052
  - 1162074204
  - 1072681815
  - 1070471996
  - 1398249245
  - 1510269826
  - 1263953596
  - 1185457530
  - 1310984791
  - 1301174235
  - 1465354533
  - 1227152968
  - 1740760630
  - 1279747448
  - 1473281847
  - 1595839251
  - 1074354585
  - 1127491908
  - 1210987817
  - 1441564230
  - 1462161273
  - 1647639783
  - 1274627304
  - 1393900742
  - 1160296406
  - 1247508011
  - 1012339614
  - 1101170442
  - 1085671411
  - 1256096706
  - 1171552896
  - 1096463945
  - 1326223284
  - 1109403194
  - 1188582446
  - 1287596810
  - 1692271774
  - 1293233260
  - 1400338245
  - 1120807475
  - 1498939244
  - 1736895964
  - 1397380283
  - 1621401381

# The output channel IDs that the messages will be forwarded to. (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
output_channel_ids:
  - 1501240289 # Output Channel ID without quotes ''

# An empty list should be set like this:
# input_channel_ids: []
